### PR TITLE
Remove `sqlite3` as development dependency

### PR DESCRIPTION
**Pull request by shaunakpp**
Hello,
As per our discussion on issue #2, I have removed the dependency and sent a PR.

---
This change is [Reviewable](https://reviewable.io/reviews/cancancommunity/cancancan-mongoid/3)

### CODE REVIEW

**Review by coorasse — APPROVED** [review]

**Comment by coorasse** [comment]
The build is failing @shaunakpp , can you please look into it? Thanks

**Comment by shaunakpp** [comment]
Hi @coorasse,
I think most of the specs are fixed in PR #1, so should I pull that branch first?

**Comment by coorasse** [comment]
#1 is still failing

**Comment by shaunakpp** [comment]
Closing this as it's merged in #4

**Pull request closed without merging**
